### ISSUE TITLE
[scalability test] Data plane manager causes unnormal delay time when process a port create event with huge neighbors

### ISSUE THREAD

**Issue by Eric-Yuan** [futurewei-cloud/alcor#376] opened 2020-09-05 10:51 UTC
When I used a port manager simulator to send DPM a port create event with about 10000 neighbors, I got about 10 seconds delay to get the response message, that seems too long than I expect.

In order to investigate why the DPM takes too long to process that message, I modified the DPM's codes by removing logging and sending GRPC codes and adding some timestamp codes in each large process block. 

I resent the message and got the below debug message:
![image](https://user-images.githubusercontent.com/4905416/92302994-97942e80-efa3-11ea-8ac9-b74fc315a1c1.png)

After further investigation, I found the unproperly initialized ‘HashSet’ usage might be the root causes. A uncertain reason is that a HashSet using the default paramters to initialize, and the size of the hash buchets is very small. When continuous add entry to this HashSet it might cause continuous resizing the buckets which cost much time.

When I modified the DPM's codes again by converting some kind neighborInfoMap variables to using 'LinkedList' to intead of 'HashSet' (not all related variables yet), and resent the messages and got the new performance result:
![image](https://user-images.githubusercontent.com/4905416/92303566-9dd8d980-efa8-11ea-8ecf-8ee322ece0ae.png)

**Comment by Eric-Yuan** [comment] 2020-09-05 10:54
I will continue taking some further investigation on this issue

**Comment by xieus** [comment] 2020-09-06 06:51
@Eric-Yuan Thanks for looking into this. 

This debugging process is exactly what we need for DPM performance profiling. DPM is a very critical component where high efficiency is a basic requirement. Yes, please pushing this effort further, and do any code refactor that is necessary.

In case you haven't enabled method-level duration statistic. When deployment DPM for the test, you could turn on DEBUG logging in application.properties or yaml file (when deployed in K8s) with the following property
```
logging.level.root=DEBUG
```

Then the @DurationStatistics annotation could show the time spent on each DPM method.

**Comment by xieus** [comment] 2020-09-06 06:51
@haboy52581 FYI.

**Comment by Eric-Yuan** [comment] 2020-09-07 01:01
> @Eric-Yuan Thanks for looking into this.
> 
> This debugging process is exactly what we need for DPM performance profiling. DPM is a very critical component where high efficiency is a basic requirement. Yes, please pushing this effort further, and do any code refactor that is necessary.
> 
> In case you haven't enabled method-level duration statistic. When deployment DPM for the test, you could turn on DEBUG logging in application.properties or yaml file (when deployed in K8s) with the following property
> 
> ```
> logging.level.root=DEBUG
> ```
> 
> Then the @DurationStatistics annotation could show the time spent on each DPM method.

@xieus OK, thanks for the feed back

**Comment by haboy52581** [comment] 2020-09-07 05:41
@Eric-Yuan Thanks a lot! Since set can make sure the element uniqueness, which line you made the change? as long as it keep the same DPM behavior, I am ok for the LinkedList replacement

**Comment by Eric-Yuan** [comment] 2020-09-07 14:11
I spent some time on this issue today, and found it is not the continuous 'resize' performance cause this issue. It is the unproper 'hashcode' implementation of 'NeighborInfo' class cause this.

@Override
    public int hashCode() {
       return 1;
    }

The same 'hashCode' value makes each entry to be added to the 'HashSet' will compare all the added entries before because hash conflicts.

**Comment by haboy52581** [comment] 2020-09-07 16:10
Yes, that would be the root cause and definitely needs revision, do you have idea to generate it or I could do that @Eric-Yuan thanks!

**Comment by xieus** [comment] 2020-10-13 04:40
@Eric-Yuan Has this issue been fully resolved, or just partially resolved by PR #378?

**Comment by xieus** [comment] 2020-10-21 05:33
@Eric-Yuan @Gzure Can you please comment on this issue?

**Comment by xieus** [comment] 2020-10-21 05:33
Linked to umbrella issue #439

**Comment by haboy52581** [comment] 2020-10-26 06:33
this is already fixed per discussion with eric

**Closed** 2020-10-26 23:12 UTC
Labels: P1, perf testing
