### ISSUE TITLE
[Data-Plane Mgr] Support multiple DataPlaneClients 

### ISSUE THREAD

**Issue by xieus** [futurewei-cloud/alcor#494] opened 2020-12-02 23:59 UTC
__Issue Description__

By design, Data-plane Manager should allow multiple data plane clients coexist so that we could enable gRPC fast path and MQ scaling path. Therefore, we should have both grpcDataPlaneClient and pulsarDataPlaneClient enabled in one DPM instance. 

Currently,  DPM can't start (commit a89370932acbde3aba55d0fbf993f7e36039d925) and throw the following error message:

```
020-12-02 21:01:38.179  WARN [dataplane-service,,,] 1 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'dpmServiceImpl': Unsatisfied dependency expressed through field 'grpcDataPlaneClient'; nested exception is org.springframework.beans.factory.NoUniqueBeanDefinitionException: No qualifying bean of type 'com.futurewei.alcor.dataplane.client.DataPlaneClient' available: expected single matching bean but found 2: grpc,pulsar
2020-12-02 21:01:38.747  INFO [dataplane-service,,,] 1 --- [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
2020-12-02 21:01:38.787  INFO [dataplane-service,,,] 1 --- [           main] ConditionEvaluationReportLoggingListener :

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2020-12-02 21:01:38.791 ERROR [dataplane-service,,,] 1 --- [           main] o.s.b.d.LoggingFailureAnalysisReporter   :

***************************
APPLICATION FAILED TO START
***************************
Description:

Field grpcDataPlaneClient in com.futurewei.alcor.dataplane.service.impl.DpmServiceImpl required a single bean, but 2 were found:
        - grpc: defined in URL [jar:file:/app/AlcorDataPlaneManager-0.1.0.jar!/BOOT-INF/classes!/com/futurewei/alcor/dataplane/client/grpc/DataPlaneClientImpl.class]
        - pulsar: defined in URL [jar:file:/app/AlcorDataPlaneManager-0.1.0.jar!/BOOT-INF/classes!/com/futurewei/alcor/dataplane/client/pulsar/DataPlaneClientImpl.class]

Action:

Consider marking one of the beans as @Primary, updating the consumer to accept multiple beans, or using @Qualifier to identify the bean that should be consumed
```

__Request__

- Check if any of the recommended actions above is feasible to fix the issue
- Re-run DPM locally to validate both gRPC client and pulsar client.

**Comment by VanderChen** [comment] 2020-12-03 07:14
This bug has fixed by PR #501. The original problem was caused by my correct code being overwritten when merging.

**Closed** 2020-12-03 07:53 UTC
Labels: P0, bug
